version: 0.2

env:
  variables:
    REACT_APP_PERSON_NAME: "Tester McTesterson"
    BUCKET_NAME: "uopx-aws-cp-curtbryan-testing"
phases:
  install:
    commands:
      - n 14
  pre_build:
    commands:
      - export REACT_APP_PERSON_NAME=$REACT_APP_PERSON_NAME
      - npm ci
      - npm run test
  build:
    commands:
      - npm run build
  post_build:
    commands: 
      - aws s3 cp --recursive ./build/. s3://$BUCKET_NAME
